server:
  port: 8082
spring:
  application:
    name: award # 服务名称
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.72.148:3307/crud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  cloud:
      nacos:
        server-addr: 192.168.72.148:8848 # nacos地址
mybatis-plus:
  type-aliases-package: org.chy.award.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: #配置逻辑删除字段
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m