server:
  port: 8083
spring:
  application:
    name: awardrecord # 服务名称
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.72.148:3307/crud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  cloud:
      nacos:
        server-addr: 192.168.72.148:8848 # nacos地址
  rabbitmq:
    host: 192.168.72.148 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /draw # 虚拟主机
    username: draw # 用户名
    password: 123 # 密码
mybatis-plus:
  type-aliases-package: org.chy.awardrecord.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: #配置逻辑删除字段
